apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gfalmvbja-python
  janus-idp.io/tekton: gfalmvbja-python
  backstage.io/kubernetes-id: gfalmvbja-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfalmvbja-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
